version: "3.10"

services:
  db:
    image: postgres:13-alpine3.14
    container_name: notification_service_db
    env_file:
      - .env_docker
    ports:
      - 5432:5432

  app:
    container_name: notification_service_app
    restart: on-failure
    entrypoint: ./boot.sh
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env_docker
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: notification_service_redis
    restart: on-failure
    ports:
      - 6379:6379

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile_celery
    command: celery -A notification_service worker -l info
    env_file:
      - .env_docker
    depends_on:
      - db
      - redis

  flower:
    container_name: flower
    build:
      context: .
      dockerfile: Dockerfile_celery
    command: celery -A notification_service flower --port=5555
    ports:
      - 5555:5555
    env_file:
      - .env_docker
    depends_on:
      - celery
