# Generated by Django 3.2.13 on 2022-08-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id_notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_notification', to='main.notification'),
        ),
    ]
