# Generated by Django 3.2.13 on 2022-08-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220827_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='slug',
            new_name='tag',
        ),
    ]
